name: domain

publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #External packages
  dartz: ^0.10.0-nullsafety.1
  get_it: ^6.0.0
  equatable: ^2.0.0

  # Personal packages
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter

  # External packages
  mockito: ^5.0.2
  build_runner:
    
flutter:
  uses-material-design: true